dataSource:
  -
    host: 127.0.0.1
    name: test
    database: test
    user: root
    password: root
    port: 3306
    maxLifeTime: 120
    maxOpenConns: 10
    maxIdleConns: 5
  -
    host: 127.0.0.1
    name: test
    database: test
    user: root
    password: root
    port: 3306
    maxLifeTime: 120
    maxOpenConns: 10
    maxIdleConns: 5
kafka :
  host: 218.0.49.239
  port: 9092
redis:
  host: 127.0.0.1:6379
  password:
  db: 10
